version: '3.8'

services:
  frontend:
    # Para desarrollo local, usamos la primera etapa del Dockerfile (Node.js)
    build:
      context: ./client
      target: build
    # Forzamos a que corra el servidor de Node/Vite en lugar de Nginx
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      # Mapeamos la carpeta local para tener Hot Reload
      - ./client:/app
      # Protegemos node_modules para que use los del contenedor
      - /app/node_modules
